---
image: docker:stable
stages:
  - build
  - push
variables:
  IMAGE_LATEST: natanfelles/php-base:latest
build:
  stage: build
  script:
    - docker info
    - docker build -t natanfelles/php-base:latest .
push:
  stage: push
  only:
    - master
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $IMAGE_LATEST && docker image rm $IMAGE_LATEST
    - rm -rf /root/.docker/
